# Ex No 1.a: Basic NumPy Array Operations
Aim: To understand the basics of NumPy arrays, including creation, attributes, slicing and indexing.

Scenario: You are a financial analyst working with a dataset of monthly sales revenue for a company over a year. You need to organize and analyze this data efficiently.

Sample Dataset:
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
sales_revenue = [12000, 15000, 17000, 13000, 16000, 18000, 20000, 19000, 17500, 16000, 15000, 16500]

Task to be Performed:
1.	Create a NumPy array from the sales revenue list.
2.	Retrieve the attributes of the array (shape, size, dtype).
3.	Slice the array to get the sales revenue for the first half of the year.
4.	Index the array to get the sales revenue for May.
5.	Calculate the total sales revenue for the year.
6.	Find the month with the highest sales revenue.

Expected Output:

Shape: (12,)

Size: 12

Data type: int32

First half of the year sales revenue: [12000 15000 17000 13000 16000 18000]

Sales revenue for May: 16000

Total sales revenue for the year: 195500

Month with highest sales revenue: July


In [ ]:
months = ['January', 'February', 'March', 'April', 'May', 'June',
          'July', 'August', 'September', 'October', 'November', 'December']

sales_revenue = [12000, 15000, 17000, 13000, 16000, 18000,
                 20000, 19000, 17500, 16000, 15000, 16500]
import numpy as np

revenue = np.array(sales_revenue)


In [ ]:
print("Shape:", revenue.shape)     # (12,)
print("Size:", revenue.size)       # 12
print("Data type:", revenue.dtype) # int64 or int32 depending on system


Shape: (12,)
Size: 12
Data type: int64


In [ ]:
first_half = revenue[0:6]
print("Sales revenue (Jan–Jun):", first_half)


Sales revenue (Jan–Jun): [12000 15000 17000 13000 16000 18000]


In [ ]:
may_revenue = revenue[4]  # May is at index 4
print("Sales revenue in May:", may_revenue)


Sales revenue in May: 16000


In [ ]:
total_revenue = np.sum(revenue)
print("Total annual sales revenue:", total_revenue)


Total annual sales revenue: 195000


In [ ]:
max_index = np.argmax(revenue)
max_month = months[max_index]
max_value = revenue[max_index]

print(f"Month with highest sales: {max_month} (${max_value})")


Month with highest sales: July ($20000)


# Ex. No. 1.b: Aggregate Functions
Aim:
To use aggregate functions in NumPy for summarizing and analyzing data.

Scenario:
You are a financial analyst examining the monthly returns of different investment portfolios. You need to calculate various aggregate statistics to understand the performance and risk associated with each portfolio.

Sample Dataset:
returns_data = {
    'portfolio_A': [0.05, 0.02, 0.04, 0.03, 0.06, 0.01],
    'portfolio_B': [0.04, 0.03, 0.05, 0.02, 0.01, 0.04],
    'portfolio_C': [0.03, 0.01, 0.02, 0.03, 0.04, 0.05]
}

Task to be Performed:

1.	Create a NumPy array for each portfolio's returns.
2.	Calculate the total return for each portfolio over the six months.
3.	Calculate the mean monthly return for each portfolio.
4.	Find the portfolio with the highest mean return.
5.	Calculate the overall average return across all portfolios.
6.	Determine the variance and standard deviation of the returns for each portfolio to assess risk.


In [ ]:
import numpy as np

In [ ]:

returns_data = {
    'portfolio_A': [0.05, 0.02, 0.04, 0.03, 0.06, 0.01],
    'portfolio_B': [0.04, 0.03, 0.05, 0.02, 0.01, 0.04],
    'portfolio_C': [0.03, 0.01, 0.02, 0.03, 0.04, 0.05]
}


portfolio_A = np.array(returns_data['portfolio_A'])
portfolio_B = np.array(returns_data['portfolio_B'])
portfolio_C = np.array(returns_data['portfolio_C'])


print("Portfolio A:", portfolio_A)
print("Portfolio B:", portfolio_B)
print("Portfolio C:", portfolio_C)

Portfolio A: [0.05 0.02 0.04 0.03 0.06 0.01]
Portfolio B: [0.04 0.03 0.05 0.02 0.01 0.04]
Portfolio C: [0.03 0.01 0.02 0.03 0.04 0.05]


In [ ]:

total_return_A = np.sum(portfolio_A)
total_return_B = np.sum(portfolio_B)
total_return_C = np.sum(portfolio_C)

print(f"Total return of Portfolio A over 6 months: {total_return_A:.4f}")
print(f"Total return of Portfolio B over 6 months: {total_return_B:.4f}")
print(f"Total return of Portfolio C over 6 months: {total_return_C:.4f}")


Total return of Portfolio A over 6 months: 0.2100
Total return of Portfolio B over 6 months: 0.1900
Total return of Portfolio C over 6 months: 0.1800


In [ ]:

mean_return_A = np.mean(portfolio_A)
mean_return_B = np.mean(portfolio_B)
mean_return_C = np.mean(portfolio_C)


print(f"Mean monthly return of Portfolio A: {mean_return_A:.4f}")
print(f"Mean monthly return of Portfolio B: {mean_return_B:.4f}")
print(f"Mean monthly return of Portfolio C: {mean_return_C:.4f}")


Mean monthly return of Portfolio A: 0.0350
Mean monthly return of Portfolio B: 0.0317
Mean monthly return of Portfolio C: 0.0300


In [ ]:

mean_returns = {
    'portfolio_A': mean_return_A,
    'portfolio_B': mean_return_B,
    'portfolio_C': mean_return_C
}

best_portfolio = max(mean_returns, key=mean_returns.get)

print(f"The portfolio with the highest mean return is: {best_portfolio} ({mean_returns[best_portfolio]:.4f})")


The portfolio with the highest mean return is: portfolio_A (0.0350)


In [ ]:

all_returns = np.array(returns_data['portfolio_A'] +
                       returns_data['portfolio_B'] +
                       returns_data['portfolio_C'])


overall_average = np.mean(all_returns)

print(f"Overall average return across all portfolios: {overall_average:.4f}")


Overall average return across all portfolios: 0.0322


In [ ]:

var_A = np.var(portfolio_A)
std_A = np.std(portfolio_A)


var_B = np.var(portfolio_B)
std_B = np.std(portfolio_B)


var_C = np.var(portfolio_C)
std_C = np.std(portfolio_C)


print(f"Portfolio A - Variance: {var_A:.6f}, Standard Deviation: {std_A:.6f}")
print(f"Portfolio B - Variance: {var_B:.6f}, Standard Deviation: {std_B:.6f}")
print(f"Portfolio C - Variance: {var_C:.6f}, Standard Deviation: {std_C:.6f}")


Portfolio A - Variance: 0.000292, Standard Deviation: 0.017078
Portfolio B - Variance: 0.000181, Standard Deviation: 0.013437
Portfolio C - Variance: 0.000167, Standard Deviation: 0.012910


# Ex No 1.c: Splitting and Aggregation
Aim:
To practice slicing, indexing, splitting, and aggregating Numpy arrays.

Scenario:
You are analysing the monthly rainfall data of a region for a year. You need to extract specific information for analysis, including quarterly splits and total rainfall for each quarter.

Sample Dataset:
rainfall_data = [120, 85, 90, 110, 95, 100, 105, 85, 115, 130, 125, 140]

Task to be Performed:

1.	Create a Numpy array from the given rainfall data.
2.	Slice the array to get the rainfall data for the first quarter (January to March).
3.	Index the array to get the rainfall data for July.
4.	Split the array into four quarters and print each quarter's data.
5.	Calculate and print the total rainfall for each quarter and also print the month with the highest rainfall in each month

Expected Output:

1.	First Quarter Rainfall Data: [120 85 90]

2.	Rainfall for July: 105

3.	First Quarter Rainfall Data: [120  85  90]
    Second Quarter Rainfall Data: [110  95 100]
    Third Quarter Rainfall Data: [105  85 115]
    Fourth Quarter Rainfall Data: [130 125 140].

4.	Total Rainfall for First Quarter: 295

    Month with highest rainfall in First Quarter: Month 1 with 120

    Total Rainfall for Second Quarter: 305

    Month with highest rainfall in Second Quarter: Month 1 with 110

    Total Rainfall for Third Quarter: 305

    Month with highest rainfall in Third Quarter: Month 3 with 115

    Total Rainfall for Fourth Quarter: 395
    
    Month with highest rainfall in Fourth Quarter: Month 3 with 140


In [ ]:
rainfall_data = [120, 85, 90, 110, 95, 100, 105, 85, 115, 130, 125, 140]
rainfall = np.array(rainfall_data)

In [ ]:
first_quarter = rainfall[0:3]

print("Rainfall for First Quarter (Jan - Mar):")
print(first_quarter)


Rainfall for First Quarter (Jan - Mar):
[120  85  90]


In [ ]:

july_rainfall = rainfall[6]

print("Rainfall in July:", july_rainfall)


Rainfall in July: 105


In [ ]:
quarter1 = rainfall[0:3]
quarter2 = rainfall[3:6]
quarter3 = rainfall[6:9]
quarter4 = rainfall[9:12]

print("Rainfall for First Quarter:")
print(quarter1)
print("Rainfall for second Quarter:")
print(quarter2)
print("Rainfall for third Quarter:")
print(quarter3)
print("Rainfall for final Quarter:")
print(quarter4)




Rainfall for First Quarter:
[120  85  90]
Rainfall for second Quarter:
[110  95 100]
Rainfall for third Quarter:
[105  85 115]
Rainfall for final Quarter:
[130 125 140]


In [ ]:
total_quarter1 = np.sum(quarter1)
max_value1 = np.max(quarter1)
total_quarter2 = np.sum(quarter2)
max_value2 = np.max(quarter2)
total_quarter3 = np.sum(quarter3)
max_value3 = np.max(quarter3)
total_quarter4 = np.sum(quarter4)
max_value4 = np.max(quarter4)

print("Total rainfall for first quarter:")
print(total_quarter1)
print("Month with highest rainfall in First Quarter:")
print(max_value1)
print("Total rainfall for second quarter:")
print(total_quarter2)
print("Month with highest rainfall in second Quarter:")
print(max_value2)
print("Total rainfall for third quarter:")
print(total_quarter3)
print("Month with highest rainfall in third Quarter:")
print(max_value3)
print("Total rainfall for final quarter:")
print(total_quarter4)
print("Month with highest rainfall in final Quarter:")
print(max_value4)






Total rainfall for first quarter:
295
Month with highest rainfall in First Quarter:
120
Total rainfall for second quarter:
305
Month with highest rainfall in second Quarter:
110
Total rainfall for third quarter:
305
Month with highest rainfall in third Quarter:
115
Total rainfall for final quarter:
395
Month with highest rainfall in final Quarter:
140
